name: Build & Deploy to ECS via Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: "Rollback to specific image tag (optional)"
        required: false
        default: ""

permissions:
  id-token: write
  contents: read
  pull-requests: read

env:
  AWS_REGION: ap-south-1
  TF_DIR: terraform
  S3_BUCKET: ten-terraform-statefile
  TFVARS_FILE: terraform/dev.tfvars

jobs:
  detect-environments:
    name: Detect .tfvars Environments
    runs-on: ubuntu-latest
    outputs:
      env_list: ${{ steps.set.outputs.json_envs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect .tfvars
        id: set
        run: |
          files=$(ls ${{ env.TF_DIR }}/*.tfvars 2>/dev/null || true)
          if [ -z "$files" ]; then
            echo "No .tfvars files found."
            echo "json_envs=[]" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          envs=()
          for f in $files; do
            envs+=("$(basename "$f" .tfvars)")
          done
          json=$(printf '%s\n' "${envs[@]}" | jq -R . | jq -s -c .)
          echo "Detected envs: $json"
          echo "json_envs=$json" >> "$GITHUB_OUTPUT"

  build-deploy:
    name: Build & Deploy (per environment)
    needs: detect-environments
    if: ${{ needs.detect-environments.outputs.env_list != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJson(needs.detect-environments.outputs.env_list) }}

    # Conditionally assign environment for UAT/Prod (manual approval)
    environment: ${{ matrix.env == 'uat' || matrix.env == 'prod' && matrix.env || 'none' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::593002333172:role/BE_Github_Actions
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions

      - name: Set environment context
        run: echo "ENVIRONMENT=${{ matrix.env }}" >> $GITHUB_ENV

      - name: Parse ECR repo from tfvars
        id: parse
        run: |
          TFVARS_FILE="${{ env.TF_DIR }}/${{ matrix.env }}.tfvars"
          if [ ! -f "$TFVARS_FILE" ]; then
            echo "❌ ERROR: TFVARS_FILE '$TFVARS_FILE' not found!"
            exit 1
          fi
          ECR_REPO=$(grep '^ecr_repo' "$TFVARS_FILE" | sed 's/.*= *"\?\(.*\)"\?/\1/' | tr -d '[:space:]"')
          echo "ECR_REPO=$ECR_REPO" >> $GITHUB_ENV

      - name: Fetch secrets from AWS Secrets Manager
        id: fetch-secrets
        run: |
          SECRET_VALUE=$(aws secretsmanager get-secret-value \
            --secret-id BE_Nextgen_Secreats \
            --query SecretString \
            --output text)
          if [ -z "$SECRET_VALUE" ]; then
            echo "❌ No secret value found!"
            exit 1
          fi
          echo "$SECRET_VALUE" | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > .env
          echo "✅ Secrets saved to .env"

      - name: Load env vars from .env
        run: |
          set -o allexport
          source .env
          set +o allexport
          echo "✅ Environment variables loaded from Secrets Manager"

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        if: ${{ github.event.inputs.rollback_tag == '' }}
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker tag $ECR_REPO:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$IMAGE_TAG

      - name: Push Docker Image
        if: ${{ github.event.inputs.rollback_tag == '' }}
        run: docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:${{ env.IMAGE_TAG }}

      - name: Rollback (use existing image)
        if: ${{ github.event.inputs.rollback_tag != '' }}
        run: |
          echo "IMAGE_TAG=${{ github.event.inputs.rollback_tag }}" >> $GITHUB_ENV
          echo "⚙️ Rollback mode enabled with tag ${{ github.event.inputs.rollback_tag }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init \
            -backend-config="bucket=${{ env.S3_BUCKET }}" \
            -backend-config="key=ecs/${{ matrix.env }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -reconfigure

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform plan \
            -var "image_tag=${{ env.IMAGE_TAG }}" \
            -var-file="${{ matrix.env }}.tfvars" \
            -out=tfplan-${{ matrix.env }}

      - name: Terraform Apply (Auto for Dev)
        working-directory: ${{ env.TF_DIR }}
        if: ${{ matrix.env == 'dev' || matrix.env == 'qa'}}
        run: terraform apply -auto-approve tfplan-${{ matrix.env }}

      - name: Terraform Apply (Manual Approval for UAT/Prod)
        working-directory: ${{ env.TF_DIR }}
        if: ${{ matrix.env == 'uat' || matrix.env == 'prod' }}
        run: terraform apply tfplan-${{ matrix.env }}

      - name: Update ECS Task Definition image
        run: |
          TFVARS_FILE="${{ env.TF_DIR }}/${{ matrix.env }}.tfvars"
          if [ ! -f "$TFVARS_FILE" ]; then
            echo "❌ ERROR: TFVARS_FILE '$TFVARS_FILE' not found!"
            exit 1
          fi

          # Extract ECS cluster and service names
          CLUSTER=$(grep 'ecs_cluster' "$TFVARS_FILE" | sed 's/.*= *"\?\(.*\)"\?/\1/' | tr -d '[:space:]"')
          SERVICE=$(grep 'ecs_service' "$TFVARS_FILE" | sed 's/.*= *"\?\(.*\)"\?/\1/' | tr -d '[:space:]"')

          echo "Cluster: '$CLUSTER'"
          echo "Service: '$SERVICE'"

          if [ -z "$CLUSTER" ] || [ -z "$SERVICE" ]; then
            echo "❌ ERROR: Cluster or Service name is empty. Check TFVARS_FILE contents."
            exit 1
          fi

          # Get current task definition ARN
          TASK_DEF=$(aws ecs describe-services --cluster "$CLUSTER" --services "$SERVICE" --query 'services[0].taskDefinition' --output text)
          echo "Current Task Definition: $TASK_DEF"

          # Create updated task definition JSON with new image and remove invalid fields
          UPDATED_JSON=$(aws ecs describe-task-definition --task-definition "$TASK_DEF" \
            | jq -c --arg IMAGE "${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$IMAGE_TAG" \
              '.taskDefinition
              | .containerDefinitions[0].image=$IMAGE
              | del(.taskDefinitionArn, .revision, .status, .registeredBy, .registeredAt, .requiresAttributes, .compatibilities)')

          # Save JSON to file
          echo "$UPDATED_JSON" > new-task-def.json
          echo "✅ Generated new task definition JSON"

          # Register new task definition revision
          NEW_TASK_DEF=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json \
            --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "New Task Definition ARN: $NEW_TASK_DEF"

          # Update ECS service to use new task definition revision
          aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$NEW_TASK_DEF"
          echo "✅ Updated ECS service $SERVICE with new image tag: $IMAGE_TAG"
